const Cdata=[
    {
        id:"1",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/2h1LLOfQVZhndBRZgW4Fgg/deb47e78448277edb62a0820e2df5134/IT_Support.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"IT Support",
        about_depart:"IT support specialists evaluate and troubleshoot technology issues so equipment runs smoothly",
        li:"If you like:",
        ul1:"Solving problems",
        ul2:"Attention to detail",
        ul3:"Troubleshooting",
        salary:"$50,875 average entry-level salary ⁴",
        opening:"340,555 job openings ⁴",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Google IT Support >",
    },
    {
        id:"2",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/OvqUFDOLTCTuZjYXmMdjm/30aaef4fc0eb48a871f1e9dbd6abae74/Rectangle_3371-2.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Data Analytics",
        about_depart:"Data analysts collect, organize, and transform data to make informed business decisions",
        li:"If you like:",
        ul1:"Working with numbers",
        ul2:"Solving problems",
        ul3:"Attention to detail",
        salary:"$67,974 average entry-level salary ⁴ ",
        opening:"337,407 job openings ⁴",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Google Data  Analytics >",
    },



    {
        id:"3",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/1Wnn06AEvu2Kz6EbeusMl1/17ed331b495b4a66631acdf29713e0de/Project_Management.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Project Management",
        about_depart:"Project Managers oversee the planning and execution of projects to ensure they’re successful ",
        li:"If you like:",
        ul1:"Leading a team",
        ul2:"Writing and communications ",
        ul3:"Collaborating with others",
        salary:"$59,031 average entry-level salary ⁴ ",
        opening:"475,173 job openings ⁴ ",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Google Project Management >",
    },
    {
        id:"4",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/5oUOR5cnKHyXpTkW5ldBPJ/9e8b4ac508546f04143eda9d83a4d052/UX_Design.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"UX Design",
        about_depart:"UX designers make digital and physical products easier and more enjoyable to use",
        li:"If you like:",
        ul1:"Understanding people",
        ul2:"Thinking creatively        ",
        ul3:"Solving problem",
        salary:"$58,600 average entry-level salary ⁴",
        opening:"113,786 job openings ⁴",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Google UX Design >",
    },

    {
        id:"5",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/3GRpkgshsdRrUDZHQ34gHR/5da4de7fe0de0dfae6a52a334c009b98/Rectangle_3371-3.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Social Media",
        about_depart:"Social media specialists establish, build, and manage a company’s social media ",
        li:"If you like:",
        ul1:"Engaging with people",
        ul2:"Following trends",
        ul3:"Thinking creatively",
        salary:"$56,443 average entry-level salary ¹",
        opening:"30,937 job openings ¹ ",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Meta Social Media Marketing >",
    },
    {
        id:"6",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/3nCxc2e5XSL7YFywiYAQrK/01b32ced65312f397bc0568af443fc2c/Data_Science.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Data Science",
        about_depart:"Data scientists extract and analyze data to make informed business decisions        ",
        li:"If you like:",
        ul1:"Working with numbers  ",
        ul2:"Intellectual curiosity        ",
        ul3:"Writing and communication",
        salary:"$103,823 average entry-level salary ¹        ",
        opening:"364,000 job openings ¹ ",
        recomnd:"Recommended Professional Certificate(s)",
        company:" IBM Data Science >",
    },
    {
        id:"7",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/UkcT7vWUFEPlh6mQ1mcnT/d10f77261104d18118b9dc9fc95a876d/Rectangle_3371-1.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Cybersecurity",
        about_depart:"Cybersecurity analysts develop strategies to protect organizations from cyber-attacks and disruptions",
        li:"If you like:",
        ul1:"Problem solving",
        ul2:"Technical challenges",
        ul3:"Attention to detail"
        ,
        salary:"$59,031 average entry-level salary ⁴ ",
        opening:"475,173 job openings ⁴ ",
        recomnd:"Recommended Professional Certificate(s)",
        company:" IBM Cybersecurity Analyst >",
    },
    {
        id:"8",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/6IjLCUHULjNjXp4yoH1c4O/e01b33c6975e8ba32dd19417f5d6d3a8/Rectangle_3371-4.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Sales Development",
        about_depart:"Sales development representatives are the first point of contact for prospective customers        ",
        li:"If you like:",
        ul1:"Engaging with people ",
        ul2:"Building relationships",
        ul3:"Understanding people's needs ",
        
        salary:"$51,324 average entry-level salary ¹ ",
        opening:"207,400 job openings ¹",
        recomnd:"Recommended Professional Certificate(s)",
        company:" Salesforce Sales Development >",
    },
    {
        id:"9",
        imgsrc:"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://images.ctfassets.net/wp1lcwdav1p1/6fa8AznUJX75vC6fJZ4tkD/128b9bd8916d7814aaef2086d5aceaa6/Rectangle_3371-5.png?auto=format%2Ccompress&dpr=1&w=450&h=200&q=40",
        department:"Cloud Development",
        about_depart:"Cloud developers analyze customer needs and design systems and solutions for the cloud",
        li:"If you like:",
        ul1:"Managing projects ",
        ul2:"Maintaining databases",
        ul3:"New technology",
        salary:"$81,312 average entry-level salary ¹",
        opening:"92,243 job openings ¹",
        recomnd:"Recommended Professional Certificate(s)",
        company:" IBM Full Stack Cloud Developer >",
    },
   
    
]

export default Cdata;